CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"adreass" text NOT NULL,
	"birthdate" date NOT NULL,
	"cep" text NOT NULL,
	"city" text NOT NULL,
	"complement" text,
	"cpf" text NOT NULL,
	"email" text NOT NULL,
	"spent_money" numeric NOT NULL,
	"orgs" varchar[] NOT NULL,
	"games" varchar[] NOT NULL,
	"events" varchar[] NOT NULL,
	"products" varchar NOT NULL,
	"platforms" varchar[] NOT NULL,
	"gender" varchar NOT NULL,
	"neighborhood" text NOT NULL,
	"nick" text NOT NULL,
	"number" integer NOT NULL,
	"password" text NOT NULL,
	"phone_number" text NOT NULL,
	"state" text NOT NULL
);
